apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-microservice
  name: auth-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-microservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-microservice
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/microservices-dev-459902/images-registry/auth-microservice
        name: auth-microservice
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: auth-microservice-secrets
              key: database_url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-microservice-secrets
              key: jwt_secret
        resources: {}
status: {}
