version: '3'
services:
  nats-server:
    image: nats:latest

  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: us-central1-docker.pkg.dev/microservices-dev-459902/images-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  auth-microservice:
    build: 
      context: ./auth-microservice
      dockerfile: dockerfile.prod
    image: us-central1-docker.pkg.dev/microservices-dev-459902/images-registry/auth-microservice
    environment:
      - PORT=${AUTH_MICROSERVICE_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL_PROD}
      - JWT_SECRET=${JWT_SECRET}

  products-microservice:
    build:
      context: ./products-microservice
      dockerfile: dockerfile.prod
    image: us-central1-docker.pkg.dev/microservices-dev-459902/images-registry/products-microservice
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-microservice:
    build:
        context: ./orders-microservice
        dockerfile: dockerfile.prod
        args:
          - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: us-central1-docker.pkg.dev/microservices-dev-459902/images-registry/orders-microservice
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  payments-microservice:
    build:
      context: ./payments-microservice
      dockerfile: dockerfile.prod
    image: us-central1-docker.pkg.dev/microservices-dev-459902/images-registry/payments-microservice
    ports:
      - ${PAYMENTS_MICROSERVICE_PORT}:${PAYMENTS_MICROSERVICE_PORT}
    environment:
      - PORT=${PAYMENTS_MICROSERVICE_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}