apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders-microservice
  name: orders-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-microservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders-microservice
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/microservices-dev-459902/images-registry/orders-microservice
        name: orders-microservice
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: nats://nats
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: orders-microservice-secrets
              key: database_url
        resources: {}
status: {}
